# Generated by Django 4.0.4 on 2022-04-23 23:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='available',
            field=models.BooleanField(default=False),
            preserve_default=False,
        ),
    ]
