# Generated by Django 4.0.4 on 2022-04-23 20:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0003_remove_profile_contacts_profile_contacts'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='requests',
        ),
    ]
