# Generated by Django 4.0.4 on 2022-04-21 02:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0005_alter_profile_contacts_alter_profile_ratings_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='ratings',
            field=models.ManyToManyField(blank=True, to='main_app.rating'),
        ),
    ]
