# Generated by Django 4.0.4 on 2022-04-23 22:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0007_alter_rating_reviewee'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='rating',
            options={'ordering': ['created_at']},
        ),
    ]
