# Generated by Django 4.0.4 on 2022-04-23 23:01

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('main_app', '0008_alter_rating_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='ratings_ive_written',
            field=models.ManyToManyField(blank=True, related_name='profile_ratings_ive_written', to='main_app.rating'),
        ),
        migrations.AlterField(
            model_name='rating',
            name='reviewee',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='user_reviewee', to=settings.AUTH_USER_MODEL),
        ),
    ]
