# Generated by Django 4.0.4 on 2022-04-21 22:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0008_alter_profile_num_seats'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='img',
            new_name='image_link',
        ),
    ]
